AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  producerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        producer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /producer
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./producer
      DockerTag: python3.10-v1
  
  receiverFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          SOME_VAR: !Ref SomeVar

      Events:
        receiver:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /receiver
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./receiver
      DockerTag: python3.10-v1
Parameters:
  SomeVar:
    Type: String
    
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  producerApi:
    Description: "API Gateway endpoint URL for Prod stage for Producer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/producer/"
  producerFunction:
    Description: "ProducerLambda Function ARN"
    Value: !GetAtt ProducerFunction.Arn
  producerFunctionIamRole:
    Description: "Implicit IAM Role created for Producer function"
    Value: !GetAtt ProducerFunctionRole.Arn
    
  receiverApi:
    Description: "API Gateway endpoint URL for Prod stage for receiver function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/receiver/"
  receiverFunction:
    Description: "receiver Lambda Function ARN"
    Value: !GetAtt receiverFunction.Arn
  receiverFunctionIamRole:
    Description: "Implicit IAM Role created for receiver function"
    Value: !GetAtt receiverFunctionRole.Arn